### ISSUE TITLE
ONNX file converison process

### ISSUE THREAD

**Issue by neeraj-ag** [galliot-us/adaptive-pose-estimation#9]
Great work on creating the TensorRT engine from the ONNX file ! 
Can you please provide more information on how was the ONNX file created? It would be of great help

Thanks !

**Comment by mrn-mln** [comment]
> 
> 
> Great work on creating the TensorRT engine from the ONNX file ! Can you please provide more information on how was the ONNX file created? It would be of great help
> 
> Thanks !

Hi, we use [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx) to export ONNX from .pb files.
